### ISSUE TITLE
Creation of 'Load SystemHealthSession' Job not available in scripts

### ISSUE THREAD

**Issue by JuleSQL** [amitmsft/MSSQLTIGERDemos#1]
Do not see a script for 'Load SystemHealthSession' Job as showed in your demonstration video. Believe this is why I can't run any reports in the 'XEventReporting' folder.

**Comment by savjani-zz** [comment]
Thanks for reporting the issue. I have fixed it now. Please use the latest CREATECOLLECTIONJob.sql file to create Load SystemHealthSession Job. Thanks !!!

**Comment by JuleSQL** [comment]
Thank You Parik! The reports are loading now after running the job, just no information to see currently. I'll test some stuff out!

**Comment by savjani-zz** [comment]
Sounds good ..Good to hear !!!
