### ISSUE TITLE
System Health Session PowerBI file gets Arithmetic Overflow on ScheduleMonitor datasource

### ISSUE THREAD

**Issue by ikdonev** [amitmsft/MSSQLTIGERDemos#2]
When I use the PBI file on large systems, I get an Arithmetic overflow on refreshing the ScheduleMonitor DS. I workaround it with changing the INTs to BIGINTs in the source query. I guess it is safe to update the master pbix here.

**Comment by banerjeeamit** [comment]
Thanks for reporting this. Please feel free to submit a change to the pbix file.
