### ISSUE TITLE
Script error with SQL-Performance-Baseline demo

### ISSUE THREAD

**Issue by mfabajwa** [amitmsft/MSSQLTIGERDemos#4]
Hi Amit, great session I must say. Appreciate the great work from MS.

I was following the SQL-Performance-Baseline demo, and receiving the below error:

PS C:\Scripts> C:\Scripts\Get-SQLPerfCounters.ps1
cmdlet Get-SQLPerfCounters.ps1 at command pipeline position 1
Supply values for the following parameters:
server: PERFTUNINGSQL14
get-counter : The specified counter could not be found.
At C:\Scripts\Get-SQLPerfCounters.ps1:75 char:15
+        $gc = (get-counter -counter $perfList)
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (:) [Get-Counter], Exception
    + FullyQualifiedErrorId : CounterApiError,Microsoft.PowerShell.Commands.GetCounterCommand
 

Please advise with this error: Because of this, SQL agent job called "DBA - PerfMon Counter Collection" is stuck.

Thanks
Faran

**Comment by savjani-zz** [comment]
Hi Faran,

Do you have default instance of SQL Server installed on PERFTUNINGSQL14 against which the job is failing? Can you also check and validate if you can see the perfmon counters for SQL Server default instance installed on your server?

**Comment by mfabajwa** [comment]
Hello
Yes it is default instance and I can see perform counters as well. A screenshot attached,
Not sure where the problem is.
RegardsFaran 

```
On Monday, 7 November 2016, 21:52, Parikshit <notifications@github.com> wrote:
```

 Hi Faran,Do you have default instance of SQL Server installed on PERFTUNINGSQL14 against which the job is failing? Can you also check and validate if you can see the perfmon counters for SQL Server default instance installed on your server?—

**Comment by savjani-zz** [comment]
Hi Faran,

In that case I would suggest you modify the SQL Agent job DBA – PerfMon Counter Collection job and replace $(ESCAPE_NONE(SRVR)) with your computer name to see if it works for you.

**Comment by mfabajwa** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Hi there
Still the same I think powershell script needs some different permissions. I will create new powershell script and copy the code from your scripts and see if that helps.
Another question What was the Visual studio version the SSRS reports were developed in?
Thanks
Faran

Sent from Yahoo Mail for iPhone

On Wednesday, November 9, 2016, 12:29 am, Parikshit notifications@github.com wrote:

Hi Faran,

In that case I would suggest you modify the SQL Agent job DBA – PerfMon Counter Collection job and replace $(ESCAPE_NONE(SRVR)) with your computer name to see if it works for you.

**Comment by savjani-zz** [comment]
Hi Faran,

You can use SSDT for visual studio 2013 to deploy the reports to any version between SQL 2008 R2 to SQL 2014.

**Comment by mfabajwa** [comment]
Hi Amit
It says on the main page that  "The SSRS Reports should be deployed on the central SSRS server which should be greater than SQL 2012.".  You said in the last email that the reports can be deployed to any version between SQL 2008 R2 to SQL 2014. Please advise.
Would the reports work in SSRS in SQL Server 2012 Express with advanced services?
Which versions of SQL Server can these reports monitor? I mean would you scripts run fine on SQL 2005 instances that I wish to monitor and baseline?
Many thanksFaran

 

    On Saturday, 12 November 2016, 5:35, Parikshit <notifications@github.com> wrote:
 

 Hi Faran,You can use SSDT for visual studio 2013 to deploy the reports to any version between SQL 2008 R2 to SQL 2014.—

**Comment by savjani-zz** [comment]
Hi Faran,

The Central SSRS server has to be SQL 2012 and above since reports are designed on SQL 2012 but the target instances to monitor can be any version between SQL 2008 R2 to SQL 2014. I haven't tested it on SQL 2005 so i don't want to claim it will work but it may work.

The reports should work on SQL Server 2012 Express with advanced services but i have not tested it but you can try and it should work.

P.S. My first name is Parikshit :)

Regards,
Parikshit

**Comment by mfabajwa** [comment]
Hi Parikshit

Sorry and thanks for correcting me.

And thanks for confirming on those questions. Much appreciated.

Regards
Faran

**Comment by mfabajwa** [comment]
Hi Parikshit
Hope you are well.
When I try to connect to a named instance and also provide port number like (SQLSERVER1\INSTANCE1, 50001), I get the below error: I am using it on SQL Server 2008. Initially it gave me error related to CPU dataset details, but when I add port number to the string, it gives below error. It looks like this particular dataset fails? Any advice would be appreciated.ThanksFaran
   
   - An error has occurred during report processing. (rsProcessingAborted)
   
   - Query execution failed for dataset 'MISC_INFO'. (rsErrorExecutingCommand)
   
   - For more information about this error navigate to the report server on the local server machine, or enable remote error
   -       
      -       



 

    On Wednesday, 10 May 2017, 17:47, Parikshit <notifications@github.com> wrote:
 

 Hi Faran,The Central SSRS server has to be SQL 2012 and above since reports are designed on SQL 2012 but the target instances to monitor can be any version between SQL 2008 R2 to SQL 2014. I haven't tested it on SQL 2005 so i don't want to claim it will work but it may work.The reports should work on SQL Server 2012 Express with advanced services but i have not tested it but you can try and it should work.P.S. My first name is Parikshit :)Regards,
Parikshit—

**Comment by mfabajwa** [comment]
Hi Parikshit

Hope you are well.

When I try to connect to a named instance and also provide port number like (SQLSERVER1\INSTANCE1, 50001), I get the below error: I am using it on SQL Server 2008. Initially it gave me error related to CPU dataset details, but when I add port number to the string, it gives below error. It looks like this particular dataset fails? Any advice would be appreciated.
Thanks
Faran

An error has occurred during report processing. (rsProcessingAborted)
Query execution failed for dataset 'MISC_INFO'. (rsErrorExecutingCommand)
For more information about this error navigate to the report server on the local server machine, or enable remote error

**Comment by savjani-zz** [comment]
Hi Faran,

You can be able to avoid that error by using the latest version of SQL Performance baseline reports. We have moved the location to following where you should be able to find the latest version of the solution
https://github.com/Microsoft/tigertoolbox/tree/master/SQL-Performance-Baseline

Regards,
Parikshit

**Comment by mfabajwa** [comment]
Hi Parikshit
Hope you are well. I tried again but still errorring out. I am putting in SQLSERVER1\INSTANCE1, 50001
I get the below error.
ThanksFaran
   
   - An error has occurred during report processing. (rsProcessingAborted)
   
   - Cannot create a connection to data source 'dba_local'. (rsErrorOpeningConnection)
   
   - Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'
 

    On Thursday, 6 July 2017, 2:45, Parikshit <notifications@github.com> wrote:
 

 Hi Faran,You can be able to avoid that error by using the latest version of SQL Performance baseline reports. We have moved the location to following where you should be able to find the latest version of the solution
https://github.com/Microsoft/tigertoolbox/tree/master/SQL-Performance-BaselineRegards,
Parikshit—

**Comment by savjani-zz** [comment]
Faran,

I think there is some issue with Kerberos configuration for your environment. You can avoid this error by using stored credentials by modifying the report.

Regards,
Parikshit

**Comment by mfabajwa** [comment]
Hi Parikshit
We have not enabled Kerberos. Thanks. Will go with your suggestion.
ThanksFaran 

    On Thursday, 12 October 2017, 22:56, Parikshit <notifications@github.com> wrote:
 

 Faran,

I think there is some issue with Kerberos configuration for your environment. You can avoid this error by using stored credentials by modifying the report.

Regards,
Parikshit

**Comment by mfabajwa** [comment]
Parikshit
If I raise a support ticket with Microsoft, would they be able to help with sorting it out?
ThanksF 

    On Friday, 13 October 2017, 9:46, Faran Altaf Bajwa <mfabajwa@yahoo.com> wrote:
 

 Hi Parikshit
We have not enabled Kerberos. Thanks. Will go with your suggestion.
ThanksFaran 

    On Thursday, 12 October 2017, 22:56, Parikshit <notifications@github.com> wrote:
 

 Faran,

I think there is some issue with Kerberos configuration for your environment. You can avoid this error by using stored credentials by modifying the report.

Regards,
Parikshit

**Comment by savjani-zz** [comment]
Yes, they should be able to help you or any SSRS developer can assist you with using the stored credentials in SSRS report.

Regards,
Parikshit

**Comment by mfabajwa** [comment]
Thanks Parikshit . Do you know which permissions should be given to the stored credentials in the SSRS reports?
RegardsFaran 

    On Saturday, 14 October 2017, 1:25, Parikshit <notifications@github.com> wrote:
 

 Yes, they should be able to help you or any SSRS developer can assist you with using the stored credentials in SSRS report.

Regards,
Parikshit

**Comment by savjani-zz** [comment]
The stored credential should have CONNECT permissions to the SQL Instance and it should be db_reader on the dba_local database to query and read the reports from the database.

Regards,
Parikshit

**Comment by mfabajwa** [comment]
Many thanks Parakshit. Much appreciated. 

    On Monday, 16 October 2017, 21:29, Parikshit <notifications@github.com> wrote:
 

 The stored credential should have CONNECT permissions to the SQL Instance and it should be db_reader on the dba_local database to query and read the reports from the database.

Regards,
Parikshit

**Comment by mrshahin** [comment]
Hi Guy's,
when run the SQL Performance Baselining Reports I can see that the graph's are empty and I think because when run the Get-SQLPerfCounters.ps1 get this error:


Get-Counter : The specified counter could not be found.
At C:\Scripts\Get-SQLPerfCounters.ps1:83 char:27
+         $gc = (get-counter <<<<  -counter $perfList) 
    + CategoryInfo          : InvalidResult: (:) [Get-Counter], Exception
    + FullyQualifiedErrorId : CounterApiError,Microsoft.PowerShell.Commands.GetCounterCommand


The SQL perfmon are already installed. Also using the last version of Report from tiger tool box.
Any idea?

**Comment by savjani-zz** [comment]
Hi @mrshahin - Is your instance name parameter specified correct? Make sure that you supply the SQLInstanceName parameter correct
